version: '3.7'
services:
  es01:
    container_name: elasticsearch
    restart: always
    build: 
            context: .
            dockerfile: Dockerfile
    image: fias/elasticsearch
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2024m -Xmx2024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - config:/usr/share/elasticsearch/config
      - snapshots:/usr/share/elasticsearch/snapshots
      - data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    expose:
      - "9200"
    networks:
      - elastic

  kibana:
    container_name: kibana 
    image: docker.elastic.co/kibana/kibana:7.5.1
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_HOST=es01
    depends_on:
      - es01
    ports:
      - 5601:5601
    expose:
      - "5601"
    networks:
      - elastic

volumes:
  data:
    driver: local
  snapshots:
    driver: local
  config:
    driver: local

networks:
  elastic:
    driver: bridge
